################################################################
## Packages / Cast
################################################################

################################################
## Customize
################################################

homeassistant:
  customize:
    ################################################
    ## Node Anchors
    ################################################

    package.node_anchors:
      customize: &customize
        package: 'cast'

      expose: &expose
        <<: *customize

#################################################
## Sonos
#################################################

cast:
  media_player:
  - host: 192.168.18.165
