################################################################
## Packages / Google Calendar
################################################################

################################################
## Customize
################################################

homeassistant:
  customize:
    ################################################
    ## Node Anchors
    ################################################

    package.node_anchors:
      customize: &customize
        package: 'Google_Calendar'

      expose: &expose
        <<: *customize

#################################################
## Google Calendar
#################################################

google:
  client_id: !secret google_cal_id
  client_secret: !secret google_cal_secret
  track_new_calendar: false
#################################################
## Automations
#################################################

automation:

 - alias: Change to nightlight and delays
   trigger:
     platform: state
     entity_id: calendar.homeassistant
     to: 'on'
   action:
     - service: input_number.set_value
       data_template:
         entity_id: input_number.current_hue_brightness
         value: '{{ states.input_number.hue_nightlight_brightness.state | float }}'
     - service: input_number.select_value
       data_template:
         entity_id: input_number.current_dimmer_brightness
         value: '{{ states.input_number.dimmer_nightlight_brightness.state | float }}'
     - service: input_number.set_value
       data:
         entity_id: input_number.kitchen_delay
         value: 2
     - service: input_number.set_value
       data:
         entity_id: input_number.bathroom_delay
         value: 2

 - alias: Change to daylight and delays
   trigger:
     platform: state
     entity_id: calendar.homeassistant
     to: 'off'
   action:
     - service: input_number.set_value
       data:
         entity_id: input_number.current_hue_brightness
         value: 255
     - service: input_number.set_value
       data:
         entity_id: input_number.current_dimmer_brightness
         value: 255
     - service: input_number.set_value
       data:
         entity_id: input_number.kitchen_delay
         value: 10
     - service: input_number.set_value
       data:
         entity_id: input_number.bathroom_delay
         value: 10
