################################################################
## Packages / Grafana
################################################################

################################################
## Customize
################################################

homeassistant:
  customize:
    ################################################
    ## Node Anchors
    ################################################

    package.node_anchors:
      customize: &customize
        package: 'grafana'

      expose: &expose
        <<: *customize


    ################################################
    ## Script
    ################################################

    script.grafana_webhook:
      <<: *customize
      friendly_name: "Grafana Webhook"
      hidden: true
      icon: mdi:webhook

################################################
## Prometheus
################################################

#prometheus:

################################################
## Panel Iframe
################################################

panel_iframe:
  grafana:
    title: 'Grafana'
    url: !secret panel_grafana_url
    icon: mdi:chart-pie

################################################
## Script
################################################

#script:
#  grafana_webhook:
#    sequence:
#      - condition: template
#        value_template: >-
#          {{ state != 'ok' and state != 'no_data' }}
#      - service: notify.syslog
#        data_template:
#          message: >
#            ruleId="{{ ruleId }}",
#            title="{{ title }}",
#            ruleUrl="{{ ruleUrl }}",
#            imageUrl="{{ imageUrl }}",
#            state="{{ state }}",
#            message="{{ message }}",
#            ruleName="{{ ruleName }}",
#            evalMatches="{{ evalMatches|pprint }}"
#      - service: notify.telegram
#        data_template:
#          message: >-
#            {{ ruleName }} is {{ state }}.
#            {% for match in evalMatches %}
#              {{ match.metric }}: {{ match.value }}
#            {% endfor %}
