################################################################
## Packages / home
################################################################

################################################
## Customize
################################################

homeassistant:
  customize:
    ################################################
    ## Node Anchors
    ################################################

    package.node_anchors:
      customize: &customize
        package: 'home'

      expose: &expose
        <<: *customize


group:
  default_view:
    view: yes
    icon: mdi:home
    control: hidden
    entities:
      - sensor.work_to_home__sean
      - sensor.home_to_work__sean
      - group.mostusedlights
