################################################################
## Packages / HTTP
################################################################

################################################
## Customize
################################################

homeassistant:
  customize:
    ################################################
    ## Node Anchors
    ################################################

    package.node_anchors:
      customize: &customize
        package: 'http'

      expose: &expose
        <<: *customize
#        haaska_hidden: false
#        homebridge_hidden: false

################################################
## HTTP
################################################

http:
#  base_url: !secret http_base_url
#  use_x_forwarded_for: true
  ip_ban_enabled: false
#  login_attempts_threshold: 5

api:

#splunk:
#  token: !secret splunk_token
#  host: 192.168.0.15
