################################################################
## Packages / Nest
################################################################

################################################
## Customize
################################################

homeassistant:
  customize:
    ################################################
    ## Node Anchors
    ################################################

    package.node_anchors:
      customize: &customize
        package: 'Nest'

      expose: &expose
        <<: *customize

#################################################
## Nest
#################################################

nest:
  client_id: !secret nest_id
  client_secret: !secret nest_secret
