################################################################
## Packages / Discord
################################################################

################################################
## Customize
################################################

homeassistant:
  customize:
    ################################################
    ## Node Anchors
    ################################################

    package.node_anchors:
      customize: &customize
        package: 'discord'

#      expose: &expose
#        <<: *customize
#        haaska_hidden: false
#        homebridge_hidden: false

    ################################################
    ## Automation
    ################################################

#    automation.forward_persistent_notifications:
#      <<: *customize
#      friendly_name: "Forward Persistent Notifications"
#      icon: mdi:message-text

#    automation.telegram_restart:
#      <<: *customize
#      friendly_name: "Telegram: Restart"
#      icon: mdi:power

#    automation.telegram_roll:
#      <<: *customize
#      friendly_name: "Telegram: Roll"
#      icon: mdi:dice-multiple

################################################
## Automation
################################################

#automation:
#  - alias: forward_persistent_notifications
#    initial_state: 'on'
#    trigger:
#      - platform: event
#        event_type: call_service
#        event_data:
#          domain: persistent_notification
#          service: create
#    action:
#      - service: notify.telegram
#        data_template:
#          message: >-
#            {% set message = trigger.event.data.service_data.message %}
#            {% if 'login attempt' in message|lower %}
#              {{ message }}: http://www.ip-tracker.org/locator/ip-lookup.php?ip={{ message.split('from ')[1] }}
#            {% else %}
#              {{ message }}
#            {% endif %}

################################################
## Notify
################################################

notify:
  - name: discord
    platform: discord
    token: !secret discord_token
