################################################################
## Packages / Recorder
################################################################

################################################
## Customize
################################################

homeassistant:
  customize:
    ################################################
    ## Node Anchors
    ################################################

    package.node_anchors:
      customize: &customize
        package: 'recorder'

#      expose: &expose
#        <<: *customize
#        haaska_hidden: false
#        homebridge_hidden: false

################################################
## Recorder
################################################

recorder:
  purge_interval: 3
  purge_keep_days: 3
  db_url: !secret postgresql_url
#  exclude:
#    domains:
#      - sun
#    entities:
#      - sensor.kitchen_luminance
