################################################################
## Packages / remote
################################################################

################################################
## Customize
################################################

homeassistant:
  customize:
    ################################################
    ## Node Anchors
    ################################################

    package.node_anchors:
      customize: &customize
        package: 'remote'

      expose: &expose
        <<: *customize

#################################################
## Harmony
#################################################

remote:
  - platform: harmony
    name: Living Room
    host: 192.168.18.183
