################################################################
## Packages / System Monitor
################################################################

################################################
## Customize
################################################

homeassistant:
  customize:
    ################################################
    ## Node Anchors
    ################################################

    package.node_anchors:
      customize: &customize
        package: 'system_monitor'

      expose: &expose
        <<: *customize
#        haaska_hidden: false
#        homebridge_hidden: false

################################################
## HTTP
################################################

sensor:
  - platform: systemmonitor
    resources:
      - type: load_1m
      - type: memory_use
      - type: processor_use
