################################################################
## Packages / tado
################################################################

################################################
## Customize
################################################

homeassistant:
  customize:
    ################################################
    ## Node Anchors
    ################################################

    package.node_anchors:
      customize: &customize
        package: 'tado'

      expose: &expose
        <<: *customize

#################################################
## Tado
#################################################

tado:
  username: !secret tado_username
  password: !secret tado_password
